site_name: Romee's Blog
theme:
  name: material
  logo: assets/icons/logo.png
  favicon: assets/icons/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: default
      accent: black
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: default
      accent: default

nav:
  - Home: 'index.md'
  - Technology:
    - technology/index.md
    - Bias Variance Trade-off: 'technology/bias-variance-trade-off.md'
  - Finance:
    - finance/index.md
  - About: 'About.md'

plugins:

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/romitheguru/
      name: Romee Panchal on LinkedIn
    - icon: fontawesome/brands/medium
      link: https://medium.com/@romeepanchal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/romitheguru
    - icon: fontawesome/brands/github-alt
      link: https://github.com/romitheguru
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  Created by <a href="https://twitter.com/romitheguru"  target="_blank" rel="noopener">Romee Panchal</a>